language: node_js
node_js: stable
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_6b6d093a463f_key -iv $encrypted_6b6d093a463f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 119.45.214.222\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- npm run build
after_success:
- rm -rf root@119.45.214.222:/home/wyd/project/blog/*
- scp -o stricthostkeychecking=no -r ./public/* root@119.45.214.222:/home/wyd/project/blog/
branches:
  only:
  - master
addons:
    ssh_known_hosts: 119.45.214.222
env:
  global:
  - secure: 
